version: '3'

services:
  app:
    build: .
    container_name: rails
    command: ['./scripts/rails.sh']
    ports:
      - 3000:3000
    environment:
      DATABASE_DATABASENAME: dev_development
      DATABASE_USERNAME: dev
      DATABASE_PASSWORD: password
      DATABASE_HOST: psql
      DATABASE_PORT: 5432
      RAILS_ENV: development
    links:
      - psql
      - webpacker

  psql:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db-psql:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dev

  webpacker:
    build: .
    command: ['./scripts/webpack.sh']
    ports:
      - '3035:3035'

volumes:
  db-psql:
    driver: local
  db-webpack:
    driver: local